comp <- read.csv("C://Users/Inspiron/Desktop/Computer_Data.csv")
View(comp)
comp1 <- comp[-1]
View(comp1)
comp_norm <- as.data.frame(scale(comp1))
View(comp_norm)
pairs(comp_norm)
cor(comp_norm)
library(corpcor)
cor2pcor(cor(comp_norm))
attach(comp_norm)
m.comp <- lm(price~.,data=comp_norm)
summary(m.comp)
library(car)
vif(m.comp)
avPlots(m.comp,id.n=3,cex=0.7)
influenceIndexPlot(m.comp,id.n=3,cex=0.7)
influence.measures(m.comp)
influencePlot(m.comp,id.n=3)
new.mcomp <- lm(price~.,data = comp_norm[-c(1441,1701,3784,4478)])
summary(new.mcomp)
new1 <- lm(price~.-multi,data = comp_norm[-c(1441,1701,3784,4478)])
summary(new1)
plot(new.mcomp)
hist(residuals(new.mcomp))
