crime <- read.csv('C://Users//Inspiron//Desktop//assignments//Topics//Clustering//crime_data.csv')
View(crime)
crime1 <- crime[,-1]
View(crime1)
norm_crime <- scale(crime1)
View(norm_crime)
wss = (nrow(norm_crime)-1)*sum(apply(norm_crime, 2, var))		 
for (i in 2:8) wss[i] = sum(kmeans(norm_crime, centers=i)$withinss)
plot(1:8, wss, type="b", xlab="Number of Clusters", ylab="Within groups sum of squares")
title(sub = "K-Means Clustering Scree-Plot")
install.packages("kselection")
library(kselection)
k <- kmeans(norm_crime,5)
install.packages("animation")
library(animation)
k <- kmeans.ani(norm_crime,5)
k$centers
final <- data.frame(crime,k$cluster)
View(final)
aggregate(crime[,2:5], by=list(k$cluster), FUN=mean)
