crime <- read.csv('C://Users//Inspiron//Desktop//assignments//Topics//Clustering//crime_data.csv')
View(crime)
crime1 <- crime[,-1]
View(crime1)
norm_crime <- scale(crime1)
View(norm_crime)
distance <- dist(norm_crime,method = "euclidean")
hcluster <- hclust(distance,method = "complete")
plot(hcluster)
plot(hcluster,hang = -1)
clustcut <- cutree(hcluster,k=5)
rect.hclust(hcluster,k=5,border = "green")
clustergroup <- as.matrix(clustcut)
finalcluster <- data.frame(crime,clustergroup)
View(finalcluster)
