library(xlsx)
ewa <- read.xlsx("C://Users//Inspiron//Desktop//assignments//Topics//Clustering//EastWestAirlines.xlsx",2)
View(ewa)
ewa1 <- ewa[,-1]
norm_ewa1 <- scale(ewa1)
View(norm_ewa1)
distance <- dist(norm_ewa1,method = "euclidean")
hcluster <- hclust(distance,method = "complete")
plot(hcluster)
plot(hcluster,hang=-1)
cut <- cutree(hcluster,k=10)
rect.hclust(hcluster,k=10,border = "red")
ClusterGroup <- as.matrix(cut)
finalcluster <- data.frame(ewa,ClusterGroup)
View(finalcluster)
