install.packages("naivebayes")
install.packages("psych")
install.packages("e1071")
install.packages("mlbench")
library(naivebayes)
library(psych)
library(e1071)
library(mlbench)
library(gmodels)
library(tm)
library(caret)

salary_train <- read.csv(file.choose())
summary(salary_train)
str(salary_train)
View(salary_train)

ggplot(data=salary_train,aes(x=salary_train$Salary, y = salary_train$age, fill = salary_train$Salary)) +
  geom_boxplot() +  ggtitle("Box Plot")

plot(salary_train$workclass,salary_train$Salary)
plot(salary_train$education,salary_train$Salary)
plot(salary_train$educationno,salary_train$Salary)
plot(salary_train$maritalstatus,salary_train$Salary)
plot(salary_train$occupation,salary_train$Salary)
plot(salary_train$relationship,salary_train$Salary)
plot(salary_train$race,salary_train$Salary)
plot(salary_train$sex,salary_train$Salary)
ggplot(data=salary_train,aes(x=salary_train$Salary, y = salary_train$capitalgain, fill = salary_train$Salary)) +  geom_boxplot() +  ggtitle("Box Plot")
ggplot(data=salary_train,aes(x=salary_train$Salary, y = salary_train$capitalloss, fill = salary_train$Salary)) +  geom_boxplot() +  ggtitle("Box Plot")
ggplot(data=salary_train,aes(x=salary_train$Salary, y = salary_train$hoursperweek, fill = salary_train$Salary)) +  geom_boxplot() +  ggtitle("Box Plot")
plot(salary_train$native,salary_train$Salary)

salary_test <- read.csv(file.choose())
summary(salary_test)
str(salary_test)
View(salary_test)

model1 <- naive_bayes(salary_train$Salary~.,data=salary_train,laplace = 3)
model1
summary(model1)
pred <- predict(model1,salary_test[,1:13])
table(pred==salary_test$Salary)
mean(pred==salary_test$Salary)
confusionMatrix(pred,salary_test$Salary)
CrossTable(pred, salary_test$Salary, prop.chisq = FALSE, prop.t = FALSE, prop.r = FALSE,            dnn = c('predicted', 'actual'))
