toyota <- read.csv("C://Users/Inspiron/Downloads/ToyotaCorolla.csv")
View(toyota)
tc <- toyota[,-c(1,2,5,6,8,10,11,12,15,19:38)]
View(tc)
tc1 <- as.data.frame(scale(tc))
View(tc1)
pairs(tc1)
cor(tc1)
library(corpcor)
cor2pcor(cor(tc1))
attach(tc1)
model.tc1 <- lm(Price~.,data=tc1)
summary(model.tc1)
avPlots(model.tc1,id.n=3)
library(car)
influence.measures(model.tc1)
influenceIndexPlot(model.tc1,id.n=3,cex=0.7)
influencePlot(model.tc1,id.n=3)
vif(model.tc1)
new.tc1 <- lm(Price~.,data = tc1[-c(81,222,602,961)])
summary(new.tc1)
new.tc2 <- lm(Price~.Doors,data = tc1[-c(81,222,961)])
summary(new.tc2)              
plot(new.tc1)
hist(residuals(new.tc1))
